### ISSUE TITLE
Anonymize PRA data with avatar

### ISSUE THREAD

**Issue by olivierabz** [octopize/octopize-linkage#5]

**Comment by b-rodrigues** [comment]
question: should I anonymize the data first, then split it? or split first and then anonymize separately? I think it makes more sense to anonymize first then split, because  if you think about it, even though in real world scenario the datasets "are split" because one administration collects some features, and other administration collects other features, one could assume that these features actually would all be included in an hypothetical "super-dataset". So in our tests here, the `pra` dataset would be this super-dataset containing all features, so it should be anonymized first and then split, to mimick the real-case scenario... 

or maybe not? What do you think?

**Comment by olivierabz** [comment]
> question: should I anonymize the data first, then split it? or split first and then anonymize separately? I think it makes more sense to anonymize first then split, because if you think about it, even though in a real world scenario the datasets "are split" because one administration collects some features, and another administration collects other features, one could assume that these features actually would all be included in an hypothetical "super-dataset". So in our tests here, the `pra` dataset would be this super-dataset containing all features, so it should be anonymized first and then split, to mimick the real-case scenario...
> 
> or maybe not? Because on the other hand, even if we accept the existence of this super-dataset, in a real-world scenario, the small datasets will get anonymized separately.
> 
> What do you think?

I believe that if we wish to reproduce what will happen in practice, we should first split full original then anonymize each part separately.

When anonymizing each part, we may see that an individual's data will change in one way at source A and change in a different way in source B. We will then need to understand how this impact linkage.

**Comment by olivierabz** [comment]
@b-rodrigues I have added a script to perform anonymization of the two parts of the PRA dataset. The code was more or less there, so I pushed it. Feel free to explore and modify it if you need.
